[project]
name = "pywal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorthief>=0.2.1",
    "modern-colorthief>=0.1.7",
]
